from __future__ import annotations
import typer
from .inventory import load_inventory, get_cluster
from .agent import EKSAgent
from .reporting.renderer import render_health, render_incident
from .reporting.emailer import send_email

app = typer.Typer(no_args_is_help=True)

def run_one(inventory: str, cluster: str, incident: bool, email: bool):
    cfg = get_cluster(load_inventory(inventory), cluster)
    agent = EKSAgent(cfg)
    report = agent.collect()
    path = agent.save(report)
    text = render_incident(report) if incident else render_health(report)
    typer.echo(text)
    typer.echo(f"\nJSON report: {path}")
    if email:
        subject = f"[{report.overall_health}] EKS {report.cluster} health"
        send_email(subject, text + "\n\nJSON report generated by EKS SRE Agent.", cfg.email_recipients)

@app.command()
def health(
    inventory: str = typer.Option(...),
    cluster: str | None = typer.Option(None),
    all: bool = typer.Option(False, "--all"),
    email: bool = typer.Option(False, "--email"),
):
    inv = load_inventory(inventory)
    if all:
        for cfg in inv.clusters:
            run_one(inventory, cfg.cluster_name, False, email)
    elif cluster:
        run_one(inventory, cluster, False, email)
    else:
        raise typer.BadParameter("Use --cluster NAME or --all")

@app.command()
def incident(
    inventory: str = typer.Option(...),
    cluster: str = typer.Option(...),
    email: bool = typer.Option(False, "--email"),
):
    run_one(inventory, cluster, True, email)

if __name__ == "__main__":
    app()
